### ISSUE TITLE
2.2.5: misnamed file simply-static/src/integrations/class-cookieyes-Integration.php (fatal regression)

### ISSUE THREAD

**Issue by mmokrejs** [patrickposner/simply-static#104]
Hi,
  I cannot find a way to open a Ticket at TRAC https://plugins.trac.wordpress.org/changeset/2856450/ but the file `wp-content/plugins/simply-static/src/integrations/class-cookieyes-Integration.php` should be named `wp-content/plugins/simply-static/src/integrations/class-cookieyes-integration.php` with lowercase `i`. Because the `include` failed it completely broke the Wordpress installation. Hurry up!

**Comment by jonathandhn** [comment]
Me too

WordPress 6.1, automatic upgrade to Simply Static 2.2.5.

I've seen a lot of website crashing, we need to open a ticket with the WordPress dev team, if X WordPress fail on given automatic plugin upgrade, automatic upgrade must stop.

```
Détails de l’erreur
======================
Une erreur de type E_ERROR a été causée dans la ligne 45 du fichier /home/exemple.com/public_html/wp-content/plugins/simply-static/src/class-integrations.php. Message d’erreur : Uncaught Error: Failed opening required '/home/exemple.com/public_html/wp-content/plugins/simply-static/src/integrations/class-cookieyes-integration.php' (include_path='.:/usr/local/lsws/lsphp81/share/pear:/usr/local/lsws/lsphp81/share/php:/usr/share/pear:/usr/share/php') in /home/exemple.com/public_html/wp-content/plugins/simply-static/src/class-integrations.php:45
Stack trace:
#0 /home/exemple.com/public_html/wp-content/plugins/simply-static/src/class-integrations.php(16): Simply_Static\Integrations->includes()
#1 /home/exemple.com/public_html/wp-content/plugins/simply-static/src/class-ss-plugin.php(135): Simply_Static\Integrations->load()
#2 /home/exemple.com/public_html/wp-content/plugins/simply-static/simply-static.php(50): Simply_Static\Plugin::instance()
#3 /home/exemple.com/public_html/wp-includes/class-wp-hook.php(308): simply_static_run_plugin()
#4 /home/exemple.com/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#5 /home/exemple.com/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#6 /home/exemple.com/public_html/wp-settings.php(480): do_action()
#7 /home/exemple.com/public_html/wp-config.php(123): require_once('...')
#8 /home/exemple.com/public_html/wp-load.php(50): require_once('...')
#9 /home/exemple.com/public_html/wp-login.php(12): require('...')
#10 {main}
  thrown
```

**Comment by timwuhaotian** [comment]
Same here, the capital I is causing website fatal error

**Comment by yefimg** [comment]
Same here

Wordpress 6.1.1, Simply Static 2.2.5

```
[Sun Jan 29 19:07:09.557622 2023] [php:warn] [pid 5765] [client 172.21.0.7:42910] PHP Warning:  require_once(/var/www/html/wp-content/plugins/simply-static/src/integrations/class-cookieyes-integration.php): Failed to open stream: No such file or directory in /var/www/html/wp-content/plugins/simply-static/src/class-integrations.php on line 45

[Sun Jan 29 19:07:09.557684 2023] [php:error] [pid 5765] [client 172.21.0.7:42910] PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/html/wp-content/plugins/simply-static/src/integrations/class-cookieyes-integration.php' (include_path='.:/usr/local/lib/php') in /var/www/html/wp-content/plugins/simply-static/src/class-integrations.php:45\nStack trace:\n#0 /var/www/html/wp-content/plugins/simply-static/src/class-integrations.php(16): Simply_Static\\Integrations->includes()\n#1 /var/www/html/wp-content/plugins/simply-static/src/class-ss-plugin.php(135): Simply_Static\\Integrations->load()\n#2 /var/www/html/wp-content/plugins/simply-static/simply-static.php(50): Simply_Static\\Plugin::instance()\n#3 /var/www/html/wp-includes/class-wp-hook.php(308): simply_static_run_plugin('')\n#4 /var/www/html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)\n#5 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#6 /var/www/html/wp-settings.php(480): do_action('plugins_loaded')\n#7 /var/www/html/wp-config.php(133): require_once('/var/www/html/w...')\n#8 /var/www/html/wp-load.php(50): require_once('/var/www/html/w...')\n#9 /var/www/html/wp-blog-header.php(13): require_once('/var/www/html/w...')\n#10 /var/www/html/index.php(17): require('/var/www/html/w...')\n#11 {main}\n  thrown in /var/www/html/wp-content/plugins/simply-static/src/class-integrations.php on line 45
```

**Comment by gp-krzysiek** [comment]
Same here

WordPress 6.1.1, automatic update to Simply Static 2.2.5.

**Comment by patrickposner** [comment]
Fixed now, and the update is rolled out to w.org.
I'm leaving this open for a while if others hit the same problem.
