### ISSUE TITLE
Fatal error: Uncaught TypeError: mb_check_encoding()

### ISSUE THREAD

**Issue by jpeevi** [patrickposner/simply-static#13]
Stack Trace:

```

Fatal error: Uncaught TypeError: mb_check_encoding(): Argument #1 ($value) must be of type ?array, string given, called in /var/www/spiruwaystagging.atlr.me/wp-includes/wp-db.php on line 3006 and defined in /var/www/spiruwaystagging.atlr.me/wp-content/plugins/simply-static/vendor/symfony/polyfill-mbstring/bootstrap80.php:45 Stack trace: #0 /var/www/spiruwaystagging.atlr.me/wp-includes/wp-db.php(3006): mb_check_encoding() #1 /var/www/spiruwaystagging.atlr.me/wp-includes/wp-db.php(3117): wpdb->check_ascii() #2 /var/www/spiruwaystagging.atlr.me/wp-includes/wp-db.php(2452): wpdb->strip_invalid_text() #3 /var/www/spiruwaystagging.atlr.me/wp-includes/wp-db.php(2327): wpdb->process_fields() #4 /var/www/spiruwaystagging.atlr.me/wp-includes/option.php(487): wpdb->update() #5 /var/www/spiruwaystagging.atlr.me/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_OptionLock.php(27): update_option() #6 /var/www/spiruwaystagging.atlr.me/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_QueueRunner.php(105): ActionScheduler_OptionLock->set() #7 /var/www/spiruwaystagging.atlr.me/wp-includes/class-wp-hook.php(303): ActionScheduler_QueueRunner->maybe_dispatch_async_request() #8 /var/www/spiruwaystagging.atlr.me/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters() #9 /var/www/spiruwaystagging.atlr.me/wp-includes/plugin.php(470): WP_Hook->do_action() #10 /var/www/spiruwaystagging.atlr.me/wp-includes/load.php(1097): do_action() #11 [internal function]: shutdown_action_hook() #12 {main} thrown in /var/www/spiruwaystagging.atlr.me/wp-content/plugins/simply-static/vendor/symfony/polyfill-mbstring/bootstrap80.php on line 45

````

WordPress Version: 5.8
PHP Version: 8.0.9
Plugin Version 2.1.4.2

**Comment by jpeevi** [comment]
This was due to the lack of mbstrng extension on the server.
