### ISSUE TITLE
Builds fail on fresh install of latest Wordpress version (5.9.1)

### ISSUE THREAD

**Issue by Inclushe** [patrickposner/simply-static#27]
I noticed that I was getting this error attempting to build one of our sites: `Not valid HTML fragment!.wp-block-image...`
I went ahead an created a fresh local instance of WordPress 5.9.1 on my local machine with only Simply Static installed from the Plugins > Add New menu.
Builds fail on this fresh install at the same exact spot.
I am running MAMP and also using this on WPEngine, which I understand are unsupported, but it looks like it's not a platform issue.

Here is the debug log:
```
[2022-02-23 20:05:30] [class-ss-plugin.php:261] Received request to start generating a static archive
[2022-02-23 20:05:33] [class-ss-archive-creation-job.php:61] Starting a job; no job is presently running
[2022-02-23 20:05:33] [class-ss-archive-creation-job.php:62] Here's our task list: setup, fetch_urls, create_zip_archive, wrapup
[2022-02-23 20:05:33] [class-ss-archive-creation-job.php:76] Pushing first task to queue: setup
[2022-02-23 20:05:33] [class-ss-archive-creation-job.php:105] Current task: setup
[2022-02-23 20:05:33] [class-ss-archive-creation-job.php:121] Performing task: setup
[2022-02-23 20:05:33] [class-ss-task.php:44] Status message: [setup] Setting up
[2022-02-23 20:05:33] [class-ss-setup-task.php:32] Creating archive directory: C:\MAMP\htdocs\fresh-install\wp-content\plugins\simply-static/static-files/simply-static-1-1645646733\
[2022-02-23 20:05:33] [class-ss-setup-task.php:77] Adding origin URL to queue: http://localhost/fresh-install/
[2022-02-23 20:05:33] [class-ss-archive-creation-job.php:140] We've found our next task: fetch_urls
[2022-02-23 20:05:33] [class-ss-archive-creation-job.php:105] Current task: fetch_urls
[2022-02-23 20:05:33] [class-ss-archive-creation-job.php:121] Performing task: fetch_urls
[2022-02-23 20:05:33] [class-ss-fetch-urls-task.php:54] Total pages: 1; Pages remaining: 1
[2022-02-23 20:05:33] [class-ss-fetch-urls-task.php:57] URL: http://localhost/fresh-install/
[2022-02-23 20:05:33] [class-ss-fetch-urls-task.php:67] URL is not being excluded
[2022-02-23 20:05:33] [class-ss-url-fetcher.php:85] Fetching URL and saving it to: C:\Users\ejw98\AppData\Local\Temp/6216938d4d507-uWj4wB.tmp
[2022-02-23 20:05:33] [class-ss-url-fetcher.php:89] Filesize: 54777 bytes
[2022-02-23 20:05:33] [class-ss-url-fetcher.php:104] http_status_code: 200 | content_type: text/html; charset=UTF-8
[2022-02-23 20:05:33] [class-ss-url-fetcher.php:187] New filename for static page: /index.html
[2022-02-23 20:05:33] [class-ss-url-fetcher.php:127] Renaming temp file from C:\Users\ejw98\AppData\Local\Temp/6216938d4d507-uWj4wB.tmp to C:\MAMP\htdocs\fresh-install\wp-content\plugins\simply-static/static-files/simply-static-1-1645646733\/index.html
[2022-02-23 20:05:33] [class-ss-fetch-urls-task.php:126] Extracting URLs and replacing URLs in the static file
[2022-02-23 20:05:33] [class-ss-archive-creation-job.php:327] Error: (1) Uncaught RuntimeException: Not valid HTML fragment!.wp-block-image%7Bmargin%3A001em%7D.wp-block-imageimg%7Bvertical-align%3Abottom%7D.wp-block-image%3Anot%28.is-style-rounded%29%3Ea%2C.wp-block-image%3Anot%28.is-style-rounded%29img%7Bborder-radius%3Ainherit%7D.wp-block-image.aligncenter%7Btext-align%3Acenter%7D.wp-block-image.alignfullimg%2C.wp-block-image.alignwideimg%7Bheight%3Aauto%3Bwidth%3A100%25%7D.wp-block-image.aligncenter%2C.wp-block-image.alignleft%2C.wp-block-image.alignright%7Bdisplay%3Atable%7D.wp-block-image.aligncenter%3Efigcaption%2C.wp-block-image.alignleft%3Efigcaption%2C.wp-block-image.alignright%3Efigcaption%7Bdisplay%3Atable-caption%3Bcaption-side%3Abottom%7D.wp-block-image.alignleft%7Bfloat%3Aleft%3Bmargin%3A.5em1em.5em0%7D.wp-block-image.alignright%7Bfloat%3Aright%3Bmargin%3A.5em0.5em1em%7D.wp-block-image.aligncenter%7Bmargin-left%3Aauto%3Bmargin-right%3Aauto%7D.wp-block-imagefigcaption%7Bmargin-top%3A.5em%3Bmargin-bottom%3A1em%7D.wp-block-image.is-style-circle-maskimg%2C.wp-block-image.is-style-roundedimg%7Bborder-radius%3A9999px%7D%40supports%28%28-webkit-mask-image%3Anone%29or%28mask-image%3Anone%29%29or%28-webkit-mask-image%3Anone%29%7B.wp-block-image.is-style-circle-maskimg%7B-webkit-mask-image%3Aurl%28%27data%3Aimage%2Fsvg+xml%3Butf8%2C%3Csvgviewbox%3D%2200100100%22xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Ccirclecx%3D%2250%22cy%3D%2250%22r%3D%2250%22%3E%3C%2Fcircle%3E%27%29%3Bmask-image%3Aurl%28%27data%3Aimage%2Fsvg+xml%3Butf8%2C%3Csvgviewbox%3D%2200100100%22xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Ccirclecx%3D%2250%22cy%3D%2250%22r%3D%2250%22%3E%3C%2Fcircle%3E%27%29%3Bmask-mode%3Aalpha%3B-webkit-mask-repeat%3Ano-repeat%3Bmask-repeat%3Ano-repeat%3B-webkit-mask-size%3Acontain%3Bmask-size%3Acontain%3B-webkit-mask-position%3Acenter%3Bmask-position%3Acenter%3Bborder-radius%3A0%7D%7D.wp-block-imagefigure%7Bmargin%3A0%7D.wp-block-imagefigcaption%7Bcolor%3A%23555%3Bfont-size%3A13px%3Btext-align%3Acenter%7D.is-dark-theme.wp-block-imagefigcaption%7Bcolor%3Ahsla%280%2C0%25%2C100%25%2C.65%29%7D%3C%2Fsvg%3E%3C%2Fsvg%3E.wp-block-image%7Bmargin%3A001em%7D.wp-block-imageimg%7Bvertical-align%3Abottom%7D.wp-block-image%3Anot%28.is-style-rounded%29%3Ea%2C.wp-block-image%3Anot%28.is-style-rounded%29img%7Bborder-radius%3Ainherit%7D.wp-block-image.aligncenter%7Btext-align%3Acenter%7D.wp-block-image.alignfullimg%2C.wp-block-image.alignwideimg%7Bheight%3Aauto%3Bwidth%3A100%25%7D.wp-block-image.aligncenter%2C.wp-block-image.alignleft%2C.wp-block-image.alignright%7Bdisplay%3Atable%7D.wp-block-image.aligncenter%3Efigcaption%2C.wp-block-image.alignleft%3Efigcaption%2C.wp-block-image.alignright%3Efigcaption%7Bdisplay%3Atable-caption%3Bcaption-side%3Abottom%7D.wp-block-image.alignleft%7Bfloat%3Aleft%3Bmargin%3A.5em1em.5em0%7D.wp-block-image.alignright%7Bfloat%3Aright%3Bmargin%3A.5em0.5em1em%7D.wp-block-image.aligncenter%7Bmargin-left%3Aauto%3Bmargin-right%3Aauto%7D.wp-block-imagefigcaption%7Bmargin-top%3A.5em%3Bmargin-bottom%3A1em%7D.wp-block-image.is-style-circle-maskimg%2C.wp-block-image.is-style-roundedimg%7Bborder-radius%3A9999px%7D%40supports%28%28-webkit-mask-image%3Anone%29or%28mask-image%3Anone%29%29or%28-webkit-mask-image%3Anone%29%7B.wp-block-image.is-style-circle-maskimg%7B-webkit-mask-image%3Aurl%28%27data%3Aimage%2Fsvg+xml%3Butf8%2C%3Csvgviewbox%3D%2200100100%22xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Ccirclecx%3D%2250%22cy%3D%2250%22r%3D%2250%22%3E%27%29%3Bmask-image%3Aurl%28%27data%3Aimage%2Fsvg+xml%3Butf8%2C%3Csvgviewbox%3D%2200100100%22xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Ccirclecx%3D%2250%22cy%3D%2250%22r%3D%2250%22%3E%27%29%3Bmask-mode%3Aalpha%3B-webkit-mask-repeat%3Ano-repeat%3Bmask-repeat%3Ano-repeat%3B-webkit-mask-size%3Acontain%3Bmask-size%3Acontain%3B-webkit-mask-position%3Acenter%3Bmask-position%3Acenter%3Bborder-radius%3A0%7D%7D.wp-block-imagefigure%7Bmargin%3A0%7D.wp-block-imagefigcaption%7Bcolor%3A%23555%3Bfont-size%3A13px%3Btext-align%3Acenter%7D.is-dark-theme.wp-block-imagefigcaption%7Bcolor%3Ahsla%280%2C0%25%2C100%25%2C.65%29%7D in C:\MAMP\htdocs\fresh-install\wp-content\plugins\simply-static\vendor\voku\simple_html_dom\src\voku\helper\SimpleHtmlDom.php:176Stack trace:#0 C:\MAMP\htdocs\fresh-install\wp-content\plugins\simply-static\vendor\voku\simple_html_dom\src\voku\helper\AbstractSimpleHtmlDom.php(154): voku\helper\SimpleHtmlDom->replaceChildWithString('.wp-block-image...')#1 C:\MAMP\htdocs\fresh-install\wp-content\plugins\simply-static\src\class-ss-url-extractor.php(289): voku\helper\AbstractSimpleHtmlDom->__set('innertext', '.wp-block-image...')#2 C:\MAMP\htdocs\fresh-install\wp-content\plugins\simply-static\src\class-ss-url-extractor.php(157): Simply_Static\Url_Extractor->extract_and_replace_urls_in_html()#3 C:\MAMP\htdocs\fresh-install\wp-content\plugins\simply-static\src\tasks\class-ss-fetch-urls-task.php(129): Simply_Static\Url_Extractor->extract_and_update_urls()#4 C:\MAMP\htdocs\fresh-install\wp-content\plugins\simply-static\src\tasks\class-ss-fetch-urls-task.php(97): Simply_Static\Fetch_Urls_Task->handle_200_response(Object(Simply_Static\Page), true, true)#5 C:\MAMP\htdocs\fresh-install\wp-content\plugins\simply-static\src\class-ss-archive-creation-job.php(122): Simply_Static\Fetch_Urls_Task->perform()#6 C:\MAMP\htdocs\fresh-install\wp-content\plugins\simply-static\vendor\a5hleyrich\wp-background-processing\classes\wp-background-process.php(301): Simply_Static\Archive_Creation_Job->task('fetch_urls')#7 C:\MAMP\htdocs\fresh-install\wp-content\plugins\simply-static\vendor\a5hleyrich\wp-background-processing\classes\wp-background-process.php(175): WP_Background_Process->handle()#8 C:\MAMP\htdocs\fresh-install\wp-includes\class-wp-hook.php(307): WP_Background_Process->maybe_handle('')#9 C:\MAMP\htdocs\fresh-install\wp-includes\class-wp-hook.php(331): WP_Hook->apply_filters('', Array)#10 C:\MAMP\htdocs\fresh-install\wp-includes\plugin.php(474): WP_Hook->do_action(Array)#11 C:\MAMP\htdocs\fresh-install\wp-admin\admin-ajax.php(202): do_action('wp_ajax_nopriv_...')#12 {main}  thrown in <b>C:\MAMP\htdocs\fresh-install\wp-content\plugins\simply-static\vendor\voku\simple_html_dom\src\voku\helper\SimpleHtmlDom.php</b> on line <b>176</b>
[2022-02-23 20:05:33] [class-ss-archive-creation-job.php:269] Status message: [error] Error: (1) Uncaught RuntimeException: Not valid HTML fragment!.wp-block-image%7Bmargin%3A001em%7D.wp-block-imageimg%7Bvertical-align%3Abottom%7D.wp-block-image%3Anot%28.is-style-rounded%29%3Ea%2C.wp-block-image%3Anot%28.is-style-rounded%29img%7Bborder-radius%3Ainherit%7D.wp-block-image.aligncenter%7Btext-align%3Acenter%7D.wp-block-image.alignfullimg%2C.wp-block-image.alignwideimg%7Bheight%3Aauto%3Bwidth%3A100%25%7D.wp-block-image.aligncenter%2C.wp-block-image.alignleft%2C.wp-block-image.alignright%7Bdisplay%3Atable%7D.wp-block-image.aligncenter%3Efigcaption%2C.wp-block-image.alignleft%3Efigcaption%2C.wp-block-image.alignright%3Efigcaption%7Bdisplay%3Atable-caption%3Bcaption-side%3Abottom%7D.wp-block-image.alignleft%7Bfloat%3Aleft%3Bmargin%3A.5em1em.5em0%7D.wp-block-image.alignright%7Bfloat%3Aright%3Bmargin%3A.5em0.5em1em%7D.wp-block-image.aligncenter%7Bmargin-left%3Aauto%3Bmargin-right%3Aauto%7D.wp-block-imagefigcaption%7Bmargin-top%3A.5em%3Bmargin-bottom%3A1em%7D.wp-block-image.is-style-circle-maskimg%2C.wp-block-image.is-style-roundedimg%7Bborder-radius%3A9999px%7D%40supports%28%28-webkit-mask-image%3Anone%29or%28mask-image%3Anone%29%29or%28-webkit-mask-image%3Anone%29%7B.wp-block-image.is-style-circle-maskimg%7B-webkit-mask-image%3Aurl%28%27data%3Aimage%2Fsvg+xml%3Butf8%2C%3Csvgviewbox%3D%2200100100%22xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Ccirclecx%3D%2250%22cy%3D%2250%22r%3D%2250%22%3E%3C%2Fcircle%3E%27%29%3Bmask-image%3Aurl%28%27data%3Aimage%2Fsvg+xml%3Butf8%2C%3Csvgviewbox%3D%2200100100%22xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Ccirclecx%3D%2250%22cy%3D%2250%22r%3D%2250%22%3E%3C%2Fcircle%3E%27%29%3Bmask-mode%3Aalpha%3B-webkit-mask-repeat%3Ano-repeat%3Bmask-repeat%3Ano-repeat%3B-webkit-mask-size%3Acontain%3Bmask-size%3Acontain%3B-webkit-mask-position%3Acenter%3Bmask-position%3Acenter%3Bborder-radius%3A0%7D%7D.wp-block-imagefigure%7Bmargin%3A0%7D.wp-block-imagefigcaption%7Bcolor%3A%23555%3Bfont-size%3A13px%3Btext-align%3Acenter%7D.is-dark-theme.wp-block-imagefigcaption%7Bcolor%3Ahsla%280%2C0%25%2C100%25%2C.65%29%7D%3C%2Fsvg%3E%3C%2Fsvg%3E.wp-block-image%7Bmargin%3A001em%7D.wp-block-imageimg%7Bvertical-align%3Abottom%7D.wp-block-image%3Anot%28.is-style-rounded%29%3Ea%2C.wp-block-image%3Anot%28.is-style-rounded%29img%7Bborder-radius%3Ainherit%7D.wp-block-image.aligncenter%7Btext-align%3Acenter%7D.wp-block-image.alignfullimg%2C.wp-block-image.alignwideimg%7Bheight%3Aauto%3Bwidth%3A100%25%7D.wp-block-image.aligncenter%2C.wp-block-image.alignleft%2C.wp-block-image.alignright%7Bdisplay%3Atable%7D.wp-block-image.aligncenter%3Efigcaption%2C.wp-block-image.alignleft%3Efigcaption%2C.wp-block-image.alignright%3Efigcaption%7Bdisplay%3Atable-caption%3Bcaption-side%3Abottom%7D.wp-block-image.alignleft%7Bfloat%3Aleft%3Bmargin%3A.5em1em.5em0%7D.wp-block-image.alignright%7Bfloat%3Aright%3Bmargin%3A.5em0.5em1em%7D.wp-block-image.aligncenter%7Bmargin-left%3Aauto%3Bmargin-right%3Aauto%7D.wp-block-imagefigcaption%7Bmargin-top%3A.5em%3Bmargin-bottom%3A1em%7D.wp-block-image.is-style-circle-maskimg%2C.wp-block-image.is-style-roundedimg%7Bborder-radius%3A9999px%7D%40supports%28%28-webkit-mask-image%3Anone%29or%28mask-image%3Anone%29%29or%28-webkit-mask-image%3Anone%29%7B.wp-block-image.is-style-circle-maskimg%7B-webkit-mask-image%3Aurl%28%27data%3Aimage%2Fsvg+xml%3Butf8%2C%3Csvgviewbox%3D%2200100100%22xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Ccirclecx%3D%2250%22cy%3D%2250%22r%3D%2250%22%3E%27%29%3Bmask-image%3Aurl%28%27data%3Aimage%2Fsvg+xml%3Butf8%2C%3Csvgviewbox%3D%2200100100%22xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Ccirclecx%3D%2250%22cy%3D%2250%22r%3D%2250%22%3E%27%29%3Bmask-mode%3Aalpha%3B-webkit-mask-repeat%3Ano-repeat%3Bmask-repeat%3Ano-repeat%3B-webkit-mask-size%3Acontain%3Bmask-size%3Acontain%3B-webkit-mask-position%3Acenter%3Bmask-position%3Acenter%3Bborder-radius%3A0%7D%7D.wp-block-imagefigure%7Bmargin%3A0%7D.wp-block-imagefigcaption%7Bcolor%3A%23555%3Bfont-size%3A13px%3Btext-align%3Acenter%7D.is-dark-theme.wp-block-imagefigcaption%7Bcolor%3Ahsla%280%2C0%25%2C100%25%2C.65%29%7D in C:\MAMP\htdocs\fresh-install\wp-content\plugins\simply-static\vendor\voku\simple_html_dom\src\voku\helper\SimpleHtmlDom.php:176Stack trace:#0 C:\MAMP\htdocs\fresh-install\wp-content\plugins\simply-static\vendor\voku\simple_html_dom\src\voku\helper\AbstractSimpleHtmlDom.php(154): voku\helper\SimpleHtmlDom->replaceChildWithString('.wp-block-image...')#1 C:\MAMP\htdocs\fresh-install\wp-content\plugins\simply-static\src\class-ss-url-extractor.php(289): voku\helper\AbstractSimpleHtmlDom->__set('innertext', '.wp-block-image...')#2 C:\MAMP\htdocs\fresh-install\wp-content\plugins\simply-static\src\class-ss-url-extractor.php(157): Simply_Static\Url_Extractor->extract_and_replace_urls_in_html()#3 C:\MAMP\htdocs\fresh-install\wp-content\plugins\simply-static\src\tasks\class-ss-fetch-urls-task.php(129): Simply_Static\Url_Extractor->extract_and_update_urls()#4 C:\MAMP\htdocs\fresh-install\wp-content\plugins\simply-static\src\tasks\class-ss-fetch-urls-task.php(97): Simply_Static\Fetch_Urls_Task->handle_200_response(Object(Simply_Static\Page), true, true)#5 C:\MAMP\htdocs\fresh-install\wp-content\plugins\simply-static\src\class-ss-archive-creation-job.php(122): Simply_Static\Fetch_Urls_Task->perform()#6 C:\MAMP\htdocs\fresh-install\wp-content\plugins\simply-static\vendor\a5hleyrich\wp-background-processing\classes\wp-background-process.php(301): Simply_Static\Archive_Creation_Job->task('fetch_urls')#7 C:\MAMP\htdocs\fresh-install\wp-content\plugins\simply-static\vendor\a5hleyrich\wp-background-processing\classes\wp-background-process.php(175): WP_Background_Process->handle()#8 C:\MAMP\htdocs\fresh-install\wp-includes\class-wp-hook.php(307): WP_Background_Process->maybe_handle('')#9 C:\MAMP\htdocs\fresh-install\wp-includes\class-wp-hook.php(331): WP_Hook->apply_filters('', Array)#10 C:\MAMP\htdocs\fresh-install\wp-includes\plugin.php(474): WP_Hook->do_action(Array)#11 C:\MAMP\htdocs\fresh-install\wp-admin\admin-ajax.php(202): do_action('wp_ajax_nopriv_...')#12 {main}  thrown in <b>C:\MAMP\htdocs\fresh-install\wp-content\plugins\simply-static\vendor\voku\simple_html_dom\src\voku\helper\SimpleHtmlDom.php</b> on line <b>176</b>

```

**Comment by patrickposner** [comment]
Hey @Inclushe ,

It's not directly related to Simply Static.

As the error message indicates, it's a problem in the current TwentyTwentyTwo theme as their image block does not produce valid HTML.

You can verify that by adding the page to a validator: https://validator.w3.org/
