### ISSUE TITLE
Error on Mac Local

### ISSUE THREAD

**Issue by ediong** [patrickposner/simply-static#76]
This is the error I get when I want to generate with LocalWP on MacOS. When I restore to 2.1.9 it works normal.

[2022-12-19 10:04:41] Error: (1) Uncaught ValueError: RecursiveDirectoryIterator::__construct(): Argument #1 ($directory) cannot be empty in /Users/****/Local Sites/extra/app/public/wp-content/plugins/simply-static/src/tasks/class-ss-transfer-files-locally-task.php:125 Stack trace: #0 /Users/****/Local Sites/extra/app/public/wp-content/plugins/simply-static/src/tasks/class-ss-transfer-files-locally-task.php(125): RecursiveDirectoryIterator->__construct('', 4096) #1 /Users/****/Local Sites/extra/app/public/wp-content/plugins/simply-static/src/class-ss-plugin.php(860): Simply_Static\Transfer_Files_Locally_Task::delete_local_directory_static_files('', Object(Simply_Static\Options)) #2 /Users/****/Local Sites/extra/app/public/wp-includes/class-wp-hook.php(308): Simply_Static\Plugin->maybe_clear_directory('') #3 /Users/****/Local Sites/extra/app/public/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array) #4 /Users/****/Local Sites/extra/app/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #5 /Users/****/Local Sites/extra/app/public/wp-content/plugins/simply-static/src/tasks/class-ss-setup-task.php(64): do_action('ss_after_setup_...') #6 /Users/****/Local Sites/extra/app/public/wp-content/plugins/simply-static/src/class-ss-archive-creation-job.php(122): Simply_Static\Setup_Task->perform() #7 /Users/****/Local Sites/extra/app/public/wp-content/plugins/file-renaming-on-upload-pro/vendor/a5hleyrich/wp-background-processing/classes/wp-background-process.php(303): Simply_Static\Archive_Creation_Job->task('setup') #8 /Users/****/Local Sites/extra/app/public/wp-content/plugins/file-renaming-on-upload-pro/vendor/a5hleyrich/wp-background-processing/classes/wp-background-process.php(177): WP_Background_Process->handle() #9 /Users/****/Local Sites/extra/app/public/wp-includes/class-wp-hook.php(308): WP_Background_Process->maybe_handle('') #10 /Users/****/Local Sites/extra/app/public/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array) #11 /Users/****/Local Sites/extra/app/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #12 /Users/****/Local Sites/extra/app/public/wp-admin/admin-ajax.php(188): do_action('wp_ajax_wp_arch...') #13 {main} thrown in /Users/****/Local Sites/extra/app/public/wp-content/plugins/simply-static/src/tasks/class-ss-transfer-files-locally-task.php on line 125

**Comment by patrickposner** [comment]
Seems to be related so I post the link to w.org here: https://wordpress.org/support/topic/updated-to-version-2-2-and-is-no-loger-working/#post-16302345

**Comment by ediong** [comment]
I am using LocalWP on MacOS. I reverted to 2.1.9 and it's working now. I may have to wait for next update. I have two installations and both returned the errors.

**Comment by patrickposner** [comment]
Hey @ediong,

I just pushed a little fix that may help here.

If you download the file here: https://github.com/patrickposner/simply-static/blob/master/src/class-ss-plugin.php and replace it with the existing one in your directory, it should prevent failing.

**Comment by ediong** [comment]
Okay. I will try and revert ASAP. Thank you.

**Comment by ediong** [comment]
@patrickposner Thank you for the fix. Everything is back to normal now.

**Comment by patrickposner** [comment]
Awesome, I close the issue and prepare the release!
